# Dockerfile.web

FROM python:3.8.12

WORKDIR /lauretta

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY requirements-web.txt ./

RUN python3.8 -m pip install --upgrade pip
RUN pip3.8 install -r requirements-web.txt
RUN apt-get update && apt-get install -y netcat

# Copy files after installation to prevent reinstalling dependencies during docker build
COPY app ./app
COPY docs/cameras.txt ./docs
COPY docs/zones.txt ./docs

# update working directory after installations
WORKDIR /lauretta/app

ENV PYTHONPATH "${PYTHONPATH}"
