# Dockerfile

# pull the official docker image
FROM python:3.8.12

COPY app .

# set work directory
# WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY requirements-web.txt .
COPY cameras.txt .
COPY zones.txt .

RUN python -m pip install --upgrade pip
RUN pip3.8 install -r requirements-web.txt
RUN apt-get update && apt-get install -y netcat



# WORKDIR /app/FairMOT/DCNv2
ENV PYTHONPATH "${PYTHONPATH}"
# set work directory
# WORKDIR /app
