# Dockerfile.web

FROM python:3.8.12

WORKDIR /app

COPY app .

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY requirements-web.txt .
COPY cameras.txt .
COPY zones.txt .

RUN python3.8 -m pip install --upgrade pip
RUN pip3.8 install -r requirements-web.txt
RUN apt-get update && apt-get install -y netcat

ENV PYTHONPATH "${PYTHONPATH}"
